[project]
name = "resume-match-engine"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.6",
    "plotly>=6.3.0",
    "streamlit>=1.49.1",
]
