services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ResumeRelevancy
      POSTGRES_USER: shreesha
      POSTGRES_PASSWORD: shreeshaaithal
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      # Persist data
      - postgres_data:/var/lib/postgresql/data
      # Optional: Mount initialization scripts
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      # Optional: Mount custom postgresql.conf
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shreesha -d Userbase_socialOps"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge